name: Manual Workflow

on: 
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      a: 4
    steps:
      - name: "Afficher les valeurs a et b"
        run: echo "$a $b"
        env:
          b: 7
  
  job1:
    if: $a and $b > 0
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Afficher la valeur a et b
        run: |
          echo $a $b 
       
  job2:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Execute Python
        run: |
          python multiplication.py
