name: Manual Workflow

on: 
  workflow_dispatch:
   
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Définir les variables a et b
    env:
      a: 1
      b: 2
  
  job1:
    if: $a > 0
    runs-on : ubuntu-latest
    steps:
        - name: Afficher la valeur a et b
          run: |
            echo $a $b 
       
  job2:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Execute Python
        run: |
          python multiplication.py
