name: Manual Workflow

on: 
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      a: 4
      b: 8
    steps:
      - name: Définir 2 varaibles a et b
  
  job1:
    if: $a and $b > 0
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Afficher la valeur de a et b
        run: |
          echo $a $b 
       
  job2:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
  
      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
  
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Executer Python
        run: |
          python multiplication.py
